examples/sample.js, src/box.ts, src/content.ts, src/index.ts, src/page.ts, test/box.test.ts, test/page.test.ts
Support a page margin in the document definition.
To allow specifying the margin using common units, support strings that
include a number followed by a unit, as usual in CSS.
Support the units `pt` and `in` (inch), as well as the metric units `mm`
and `cm`.
These units can later also be used for other definitions such as
paddings in paragraphs.
Create functions to parse lengths with units and translate them to pt.
1 pt, defined as 1/72 inch is the default unit in a PDF document, all
layout and rendering is based on this unit.
Create a function to subtract edges from a box and ensure that the
resulting box cannot have negative widths or height.
=> ✨ Support page margins

examples/sample.js, src/content.ts, src/guides.ts, src/layout.ts, src/page.ts, test/layout.test.ts
Being able to see the exact edges of each rendered frame can be very
handy while developing layout algorithms.
Draw a thin colored rectangle around each frame. Support different
colors for different types of frames, depending on their `type`
attribute. Currently, there's only the `page` frame and `row` frames.
Over time, frames for multi-row paragraphs, or maybe columns will be
added.
Those guides can also be helpful for users of this library.
Introduce an optional `dev` element in the document definition for
developer-related settings. Add an optional attribute `guides` to this
structure to enable drawing of these guides.
=> ✨ Support guides to assist during development

tsconfig.json
Remove the unused directive `resolveJsonModule` from `tsconfig.json`.
Also remove `noImplicitThis`. There are no classes in this repository.
Remove outdated paths from the `includes` section.
=> 🔧 Cleanup TS config

examples/sample.js, src/content.ts, src/layout.ts, src/text.ts, test/layout.test.ts, test/text.test.ts
Running text is usually displayed with some space between the lines.
Hence, the line height is slightly larger than the font size.
CSS has a `line-height` attribute that allows to control the height of
text lines [[1]]. The default depends on the user agent, but is roughly
a factor of `1.2`, multiplied with the font size.
Introduce a text attribute `lineHeight` that supports a multiple of the
font size and defaults to `1.2`.
As in CSS, the line height can also be set on an inline element. In this
case, the height of a row is the maximum of the line heights of all
included text spans. Set this line height as the height of the "row"
frame.
Since the text baseline is currently set to the lower edge of the row,
the additional offset is added on top of each text row. This issue will
be …
=> ✨ Support lineHeight attribute

examples/sample.js, src/content.ts, src/document.ts, src/index.ts
Support adding metadata to the created PDF document.
Introduce an `info` element in the document definition with fields for
all common entries in the *Document Information Dictionary*, an optional
dictionary in a PDF file that contains metadata.
See Adobe PDF 1.7, section 10.2.1
=> ✨ Support document metadata

examples/sample.js, src/guides.ts, src/layout.ts, src/text.ts, test/layout.test.ts, test/text.test.ts
Each element in the document's `content` array is a paragraph.
When the text of a paragraph does not fit into a single line, it should
be broken into multiple lines.
This change implements a line-breaking algorithm that first splits text
into chunks of subsequent whitespace and non-whitespace characters and
measures these chunks separately. When trying to fit the chunks into a
given box, chunks of whitespace characters represent an opportunity for
a line break. When a chunks exceeds the max width, a line break is made
before that chunk, or, if that is not possible, after the exceeding
chunk. This ensures that text is rendered even when no line break is
possible. In this case, text will exceeds the margin.
A "paragraph" frame is introduced, that includes all rows of a
paragraph.
=> ✨ Support multi-line text

examples/sample.js, src/content.ts, src/layout.ts, test/layout.test.ts
This change adds support for the attributes `padding` and `margin` on
paragraphs.
As in the [CSS box model], a padding adds space between the edges of a
paragraph and its contents, while a margin surrounds a paragraph and
provides space between paragraphs.
Adjacent margins collapse into one, i.e. the bottom margin of one
paragraph is merged with the top margin of the next paragraph into a
single margin whose size is the maximum of the two margins.
This is also a feature of the [CSS box model].
Instead of shrinking the width of paragraphs to their content width,
set it to its available width. This allows for testing the effect of
margins, but it's also a precondition for right and center alignment.
[CSS box model]: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model
=> ✨ Support padding and margin on paragraphs

examples/sample.js, src/content.ts, src/graphics.ts, src/layout.ts, src/page.ts, test/graphics.test.ts, test/layout.test.ts, test/page.test.ts
To allow drawing basic graphics shapes into paragraphs, e.g. for markers
or annotations, this change introduces a new attribute `graphics` in
paragraph objects. This attribute accepts an array of graphics objects.
Supported types of graphics objects are `rect`, `line`, and `polyline`.
The coordinates of graphics objects are interpreted relative to the
padding of the paragraph. The origin of the coordinate system is the
top left corner, similar to [SVG] and the [Canvas API].
Parse the graphics objects before processing to ensure that no invalid
attributes can lead to unexpected errors during layout and render.
The parse function picks only the relevant members of a given object and
check their types.
Graphics objects are included in the paragraph frame's `objects`. Render
the drawable …
=> ✨ Support drawing rectangles, lines, and polylines

examples/sample.js, src/content.ts, src/layout.ts, src/text.ts, test/layout.test.ts
Previously all texts are aligned to the left by default. This change
adds support for the attribute textAlign on paragraphs. As in the
[CSS text-align], while setting textAlign to center, the texts
including the paddings are aligned to the center. While setting
textAlign to right, the texts including paddings are aligned to the
right. While `textAlign` is not set, align texts to the left.
[CSS text-align]: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
=> ✨ Support text alignment

examples/sample.js, src/index.ts, src/layout.ts, src/page.ts, test/layout.test.ts, test/page.test.ts, test/test-utils.ts
So far, pdf-maker could only create a single-page document.
To support longer documents, distribute content across multiple pages.
Let `layoutPage` stop when a paragraph does not fit on the page, and
return the page frame and the remaining paragraphs. Introduce a function
`layoutPages` that creates new pages for the remaining paragraphs.
This change only inserts page breaks between entire paragraphs, not
between rows. This is going to be improved later on.
Before, the page size used to be read from the page. Since the pages are
now created during rendering, this is not possible anymore. Set the page
size to A4 explicitly for now.
=> ✨ Support multi-page documents

examples/sample.js, src/content.ts, src/layout.ts, src/text.ts, test/text.test.ts
To allow arranging paragraphs horizontally, this change introduces a
content type `Columns` as an alternative to `Paragraph`.
With this change, content is no longer a sequence of paragraphs, but a
sequence of blocks, that can be either of type `Columns` or `Paragraph`.
Other type of blocks may be added later to support different layouts.
The attributes `width`, `height`, and `margin` are extracted from
`Paragraph` and declared as block attributes. They should be supported
for all kinds of blocks, regardless of their type.
A `Columns` element is an object with a `columns` array. Columns are
again blocks. The columns layout respects the `width` attribute of
individual columns and distributes the remaining space evenly across the
columns that don't have a fixed width.
Since columns are not …
=> ✨ Support columns

src/box.ts, src/document.ts, src/graphics.ts, src/text.ts, src/types.ts, test/box.test.ts, test/document.test.ts, test/graphics.test.ts, test/types.test.ts
When type checking input data, a util function is used to create a
`TypeError` with a message following the common pattern
"Expected {this}, got: {that}".
Rename this function to `typeError()`, export it, and replace manually
created type errors with this function where possible to align all error
messages to the same pattern.
Including the actual value in the error message directly conceals
certain values. For example, an empty array would be represented by the
empty string, objects as `[object Object]`. Numbers cannot be
distinguished from numeric strings. This can lead to confusing error
messages such as "Expected number, got 23".
To avoid this confusion, implement custom print functions for common
types such as strings, arrays, and objects.
Support using `optional()` without arguments …
=> ♻️ Improve type checks

examples/sample.js, src/content.ts, src/layout.ts, src/page.ts, src/pdf-annotations.ts, src/text.ts, test/page.test.ts
Support anchors on block elements by adding a unique `id` attribute.
Anchors are included as [named destinations] in the `Dests` element of
the document's [name dictionary].
Allow links to those named destinations by setting the text attribute
`link` to a hash sign (`#`) followed by the id of the referenced
element.
This approach seems simple and intuitive, it matches the way that links
to internal anchors are defined in HTML documents.
When a link starts with a hash sign, assume it's an internal link and
render it using a [goto action] to this named destination.
[named destinations]: See Adobe PDF 1.7, section 8.2.1, Destinations
https://archive.org/details/pdf1.7/page/n579/mode/2up
[name dictionary]: See Adobe PDF 1.7, section 3.6.3, Name Dictionary …
=> ✨ Support internal links

src/document.ts, src/fonts.ts, src/graphics.ts, src/images.ts, src/text.ts, src/types.ts, test/document.test.ts, test/fonts.test.ts, test/graphics.test.ts, test/images.test.ts, test/layout.test.ts, test/text.test.ts, test/types.test.ts
Type checks on nested attributes lead to nested error messages such as
`Invalid value for "foo": Invalid value for "bar": Expected …, got: …`.
This change improves those error messages by using a path-like pattern
to refer to nested attributes, e.g.:
`Invalid value for "foo / bar": Expected …, got: …`.
Array elements are already referred to using a human-readable index
number (i.e. starting at 1), for example `fonts / Test_Font / #1`.
Compared to the JSONPath equivalent `fonts.Test_Font[0]`, this appears
easier to read.
=> ♻️ Improve error messages for nested attributes

examples/sample.js, src/content.ts, src/document.ts, src/layout.ts, src/page-sizes.ts, test/layout.test.ts, test/page-sizes.test.ts
The page size of the PDF was fixed to A4. This change allows creating
PDF documents with different page sizes.
Introduce a new property `pageSize` in the document definition that
allows to set the size for all pages in the document. Different sizes
for individual pages are not yet supported.
The page size is accepted either as an object with `width` and `height`
attributes or a string with a well-known paper format, e.g. "A4". Format
strings are case sensitive, i.e. `Letter` is supported, but `letteR` is
not.
To allow for landscape orientation, the modifier `-landscape` can be
appended to a format string. All supported paper sizes are in portrait
orientation, however, for consistency, allow also `-portrait`.
Page sizes have been copied from pdf-lib to ensure the API remains
constant.
=> ✨ Support different page sizes

CHANGELOG.md, examples/sample.js, src/content.ts, src/guides.ts, src/layout.ts, src/read-block.ts, test/layout.test.ts
Support the attributes `breakBefore` and `breakAfter` on top-level
blocks to control whether a page break should or should not be inserted
before or after a block. These attributes are based on the CSS
attributes [break-before] and [break-after] which replace the deprecated
`page-break-before` and `page-break-after`. The new attributes control
not only page breaks, but also column breaks. Even though the latter is
not yet required, we may want to extend these attributes later.
Currently, only the attributes `auto`, `avoid`, and `always` are
supported, with `auto` being the default.
In case of a conflict, e.g. when a block with `breakAfter: 'avoid'` is
followed by a block with `breakBefore: 'always'`, let `always` take
precedence and insert a page break.
When guides are enabled, indicate …
=> ✨ Support block attributes to control page breaks

CHANGELOG.md, src/content.ts, src/document.ts, src/read-document.ts, test/document.test.ts, test/read-document.test.ts
PDF applications may include custom attributes in any object in the PDF document, except for the file trailer dictionary. Custom keys should be prefixed with `XX` [1].
The `info` attribute already allows for custom meta data to be added to the `Info` dictionary, however, only strings are supported in this data structure.
To allow for including larger blocks of binary data in a document, provide another attribute `customData` that accepts an object whose values can be strings or Uint8Arrays. Data added to this attribute will be included as stream objects and referenced in the *document catalog*.
Do not enforce the `XX` prefix, but leave the name to the application for maximum flexibility.
[1] See PDF 1.7, Appendix E - PDF Name Registry
https://archive.org/details/pdf1.7/page/n1017/mode/2up
=> ✨ Support custom data in document catalog

src/layout.ts, test/layout.test.ts
When rendering a document definition that includes a `header` but not a `footer`, pdfmkr would throw an error due a typo in the layout code.
This change fixes that error.
=> 🐛 Fix error when rendering header without footer

CHANGELOG.md, examples/sample.js, package-lock.json, package.json, src/content.ts, src/guides.ts, src/layout-columns.ts, src/layout.ts, src/read-block.ts, src/read-document.ts, test/layout-columns.test.ts, test/read-block.test.ts
The height of the header and the footer can be dynamic, but the page content used to be positioned relative to the edges of the page which could lead to an overlap.
This commit makes the page margin relative to the header and footer to let the page contents adjust to a dynamic header and footer height. The larger the header and footer, the less space is available for the page content. However, it is still possible to define a static layout by setting a fixed height on the header and footer.
This change requires to layout the header and footer first. However, at this point, the total page count is not yet known. Therefore, the header and footer are rendered twice, once to determine their size, and once again after all pages have been laid out to insert the total page count. This is only …
=> 💥 Make page margin relative to header/footer, bump to 0.4.0

examples/sample.js, src/content.ts, src/layout-columns.ts, src/read-block.ts, test/layout-columns.test.ts, test/read-block.test.ts
This commit adds support for a new block attribute `verticalAlign` that controls the vertical alignment within a columns block.
=> ✨ Support vertical alignment of columns

CHANGELOG.md, examples/sample.js, src/content.ts, src/read-graphics.ts, src/render-graphics.ts, test/render-graphics.test.ts
This commit adds support for a new property `lineDash` on all graphics shapes. This property accepts the dash pattern as an array of numbers, each of which defines the length (in pt) of a dash or gap, starting with the first dash. Dotted lines can be drawn by setting `lineCap` to `round` and using `0` as the length of the dash.
The same method of specifying dash patterns is actually used in SVG [1] and the HTML Canvas API [2]. PDF also supports a dash *phase*, which is not exposed by this commit [3].
[1]: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray [2]: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash [3]: See Adobe PDF 1.7, section 4.3.2, Line Dash Pattern https://archive.org/details/pdf1.7/page/n217/mode/1up
=> ✨ Support dashed and dotted lines

CHANGELOG.md, examples/sample.js, package-lock.json, package.json, src/layout.ts, src/page.ts, src/render-text.ts, test/render-text.test.ts
When a text rise was set in the last chunk of a text content object, it was not reset at the beginning of the next text object. This caused the text rise to be applied to the rest of the page.
Text rise is a text state operator [1] that is retained across text objects in a single content stream, i.e. a page.
Consequently, this commit maintains the text state across text objects within a page.
[1]: See 5.2 Text State Parameters and Operators
https://archive.org/details/pdf1.7/page/n395/mode/1up
=> 🐛 Fix text rise not always reset

src/page.ts, src/render-graphics.ts, test/page.test.ts
This commit adjusts the name of the function `getPageGraphicsState` that is related to *external graphics states* (`ExtGState` ) to `getExtGraphicsState` to better convey its purpose.
=> ♻️ Rename function related to ext graphics state

CHANGELOG.md, examples/sample.js, package-lock.json, package.json, src/content.ts, src/layout-text.ts, src/layout.ts, src/page.ts, src/read-block.ts, src/render-text.ts, src/text.ts, test/layout-text.test.ts, test/read-block.test.ts, test/render-text.test.ts, test/text.test.ts
This commit adds a new text attribute `letterSpacing`. Its behavior is similar to the CSS property `letter-spacing`. This attribute accepts a number, which is the extra character spacing in pt. The default letter spacing is 0. Positive values increase the spacing between characters, while negative values decrease it.
=> ✨ Add support for letter spacing

CHANGELOG.md, LICENSE.txt, examples/sample.js, src/arcs.ts, src/content.ts, src/read-graphics.ts, src/render-graphics.ts, src/svg-paths.ts, test/read-graphics.test.ts, test/render-graphics.test.ts, test/svg-paths.test.ts
This commit adds full support for SVG paths in `graphics`. To draw an SVG path, an element of type `path` accept an SVG path in a parameter `d`, similar to the SVG `<path>` element. Paths are expected in the syntax used by the `d` attribute of the SVG `<path>`. All path commands as described in [1] are supported.
[1] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#path_commands
=> ✨ Support drawing SVG paths

src/guides.ts, src/render-graphics.ts, src/render-image.ts, src/render-text.ts, src/utils.ts
We sometimes include conditional values in an array and then filter out the falsy values using `filter(Boolean)`. This approach requires the use of a type assertion (using `as`) to get the correct type.
This commit introduces a util function `compact`, inspired by the lodash function of the same name, that reflects the filter in its return type.
=> ♻️ Introduce util function compact

CHANGELOG.md, examples/sample.js, package-lock.json, package.json, src/render-graphics.ts, test/render-graphics.test.ts, test/render-page.test.ts
When a graphics path element had neither `lineColor` nor `fillColor` set, it was filled by default. If the fill area is empty, e.g. for a straight line, the fill remains invisible.
This commit changes the default to stroke, which is more likely to be visible.
=> 💥 Fallback to stroke for graphics, bump to 0.5.0

src/fonts.ts, src/images.ts, src/layout.ts, src/read-block.ts, src/types.ts
The `pickDefined` function strips all `undefined` values from a given object of type `T`. The return type of the function was `Partial<T>`. However, since only optional fields can be `undefined`, this function does not change the type.
This commit adjusts the return type to reflect the input type. This helps to remove some type assertions.
=> ♻️ Correct return type for pickDefined function

CHANGELOG.md, examples/sample.js, src/content.ts, src/layout-rows.ts, src/read-block.ts, test/layout-rows.test.ts
When a page break occurs inside a block with `rows`, it may be desirable to insert an extra block just before the first element on the new page, e.g. a table header.
This commit introduces a new `insertAfterBreak` property on `RowsBlock` that allows specifying a block to insert after a page break.
=> ✨ Support inserting an extra block after page break

src/document.ts, src/font-metrics.ts, src/fonts.ts, src/images.ts, src/layout-image.ts, src/layout-text.ts, src/layout.ts, src/make-pdf.ts, src/page.ts, src/render-page.ts, src/render-text.ts, src/text.ts, test/document.test.ts, test/fonts.test.ts, test/images.test.ts, test/layout-text.test.ts, test/page.test.ts, test/render-graphics.test.ts, test/render-image.test.ts, test/render-page.test.ts, test/render-text.test.ts, test/test-utils.ts, test/text.test.ts
The layout phase relied on the `pdf-lib` types `PDFFont` and `PDFImage`. In preparation of loading font and image resources on demand, this commit decouples the layout process from these PDF lib types and uses only `Font` and `Image` during layout.
Fonts are now only *loaded*, i.e. the fontkit font is being created before layout, since we need fontkit to calculate sizes. In the render phase, the fonts are embedded into the PDF. Likewise, images are loaded before layout to get their size, and embedded into the PDF in the render phase. During render, the PDF ref is attached to the `Font` and `Image` instances.
=> ♻️ Decouple layout from PDF lib types

CHANGELOG.md, src/document.ts
Previously, the Producer and Creator fields in the PDF Info dictionary have been set by pdf-lib. There was no way in PDF Maker to override it.
This commit removes the default values. Users can set these these values as needed in the document definition.
=> 🩹 Do not set default Producer and Creator

CHANGELOG.md, src/text.ts, test/layout-text.test.ts, test/text.test.ts
Consecutive newline characters were collapsed into a single newline. This commit fixes that by inserting empty text segments that represent blank lines.
=> 🐛 Preserve consecutive newlines

.gitignore
Gitignoring `*.local` keeps  `.env.local` and similar files local. This also allows for easily keeping local files and directories in the workspace.
=> 🔧 Gitignore all .local files

CHANGELOG.md, src/layout-rows.ts, test/layout-rows.test.ts, test/test-utils.ts
During the layout of a rows block, when there was not enough space left on a page for another row, the layout of that row would return an empty frame with a remainder that contained the entire row. When even this empty frame (`height: 0`) did not fit onto the old page because its margin would exceed the max height, a page break would have been inserted _before_ that frame. However, the remainder would still be prepended to the next page, resulting in a duplication of the row.
This commit fixes this bug by only prepending the remainder to the next page when the frame that accompanied this remainder is actually included in the old page, i.e. the page break is inserted _after_ that frame.
=> 🐛 Fix duplicated row after line break

src/fonts.test.ts, src/fonts.ts
To reduce the number of calls to the font loader and reuse loaded fonts, this commit introduces a cache for loaded fonts. The caching includes fontkit fonts which are now also reused.
=> ⚡️ Introduce cache for loaded fonts 

src/image-loader.test.ts, src/image-loader.ts, src/images/jpeg.test.ts, src/images/jpeg.ts, src/images/png.test.ts, src/images/png.ts
In order to decouple the image loader from the pdf-lib library, this commit introduces functions to read meta data (particularly width and height) from PNG and JPEG files.
=> ♻️ Read meta data from PNG and JPEG files

CHANGELOG.md, README.md, src/api/content.ts, src/image-loader.test.ts, src/image-loader.ts
Images need to be registered with the global `images` attribute. When loading images from the file system, this shouldn't be necessary.
This commit allows selecting images by their file name, similar to the `src` attribute in HTML `<img>` tags. When the name given in the `image` attribute of an image block is not a registered name, it is now interpreted as a file name and the image is loaded from the file system. Relative paths are resolved relative to the current working directory.
The optional `format` attribute of an image definition is removed. The image format is now auto-detected from the file content.
The `ImageStore` now caches the loaded images and errors from the image loader. This prevents loading the same image again when it is used multiple times.
=> ✨ Load images from file system

src/image-loader.test.ts, src/image-loader.ts, src/images.ts
The width and height of an image block was passed to the image loader, but never taken into account. This commit removes the `width` and `height` attributes from the `ImageSelector` type.
=> 🔥 Remove width and height from image selector

.npmignore, package-lock.json, package.json, tsconfig.json
The TypeScript compiler creates a single JavaScript file for each TypeScript module, and it insists on importing `.ts` files as `.js`. [esbuild] creates a single bundled `index.js` which may be more efficient to load than many individual files. It also supports `.ts` imports.
This commit uses [esbuild] for building the package and uses the TypeScript only to create type definitions.
An `.npmignore` file is added to exclude all files except the ones we want to publish.
[esbuild]: https://esbuild.github.io/
=> 🔧 Use esbuild, add npmignore

.npmignore, tsconfig.json
The package should not contains any internal type definitions. This commit excludes any `*.d.ts` files other than the `index.d.ts` and the `d.ts` files in the `api` folder from the package. All API is contained in this folder.
The `stripInternal` option is added to the `tsconfig.json` to allow marking any internal types or functions in this folder with `@internal`.
=> 🔧 Only include public API types in package

CHANGELOG.md, README.md, examples/src/text.js, src/api/layout.ts, src/api/text.ts
The type `Text` had a recursive definition that included an array of itself (`Text[]`). This created an unnecessary complex type that may even cause problems for the type checker. It also allowed for the unintended edge case of nested arrays (e.g. `[['foo']]`).
This commit and introduces a new, simpler type `TextSpan` that combines a `text` property with optional style properties. The `text` property also accepts nested `TextSpan` arrays. This results in a clearer and almost identical interface except for the irregular edge case of nested arrays.
The type `Text` is marked as deprecated.
=> 🗑️ Replace type Text with TextSpan

.github/workflows/test-build.yml, CHANGELOG.md, examples/README.md, package-lock.json, package.json, src/api/make-pdf.test.ts, src/image-loader.test.ts, src/images.test.ts, src/render/render-document.test.ts
Node.js version 20 is the current LTS version. Node.js 18 will be end-of-life in April 2025. This commit updates the minimum required Node.js version to 20.
Node 20 supports ESM out of the box. The WebCrypto API is available in the global scope. The `--experimental-global-webcrypto` flag is no longer needed to run the examples.
The manual exposure of the API in the global scope has been removed from the tests.
=> ⬆️ Require Node 20, npm 10

CHANGELOG.md, src/api/graphics.ts
As a first step towards a more type-safe API, this commit introduces a set of functions to create graphics shapes. Using these functions helps to create shapes with less code and better tool support. One advantage of using these functions is that they return the correct type without having to specify it explicitly.
For example, the following line of code
```ts
let r1: Rect = { type: 'rect', x: 10, y: 10, width: 200, height: 50, fillColor: 'red' };
```
can now be replaced with:
```ts
let r1 = rect(10, 10, 200, 50, { fillColor: 'red' });
```
=> ✨ Introduce API to create graphics shapes

CHANGELOG.md, src/api/text.test.ts, src/api/text.ts
This commit introduces the function `span()` to create text spans more conveniently. Using this function provides better tool support since the tooling can suggest text properties and values. Since the function returns objects with a specific type, less type annotations are required.
For example, the following line of code
```ts
let block = { text: ['Hello ', { text: 'World!', fontWeight: 'bold' }] };
```
can now be replaced with:
```ts
let block = { text: ['Hello ', span('World!', { fontWeight: 'bold' })]);
```
=> ✨Introduce API to create text spans

CHANGELOG.md, src/api/layout.ts
This commit introduces functions to create blocks more conveniently. The functions `text()` and `image()` can be used to create blocks that contain text or images. The functions `columns()` and `rows()` can be used to create blocks that contain other blocks.
Using these functions enables better suggestions in the editor. Since they return objects with a specific type, less type annotations are required in the code.
For example, the following line of code
```ts
const block: Block = {
rows: [
{ text: 'Hello World!', { fontWeight: 'bold' } },
{ image: 'liberty.jpg', height: 55, imageAlign: 'left' },
],
margin: { x: 75, y: 10 },
};
```
can now be replaced with:
```ts
const block = rows(
[
text('Hello World!', { fontWeight: 'bold' }),
image('liberty.jpg', { height: 55, imageAlign: 'left' }), …
```
=> ✨Introduce API to create blocks

CHANGELOG.md, src/api/PdfMaker.ts, src/api/document.ts, src/api/make-pdf.ts, src/font-store.ts, src/fonts.ts, src/index.ts
So far, font data had to be embedded directly within the document definition, despite being more logically associated with the renderer than the document itself. This also made it hard to inspect or debug document definitions due to the inclusion of large binary font data.
This commit introduces a new `PdfMaker` class that replaces the `makePdf` function. This class allows font data to be registered separately and reused across multiple documents. With this approach, font data is no longer part of the document definition.
Example:
```ts
const pdfMaker = new PdfMaker();
pdfMaker.registerFont(await readFile('path/to/MyFont.ttf'));
pdfMaker.registerFont(await readFile('path/to/MyFont-Bold.ttf'));
const pdf1 = await pdfMaker.makePdf(doc1);
const pdf2 = await pdfMaker.makePdf(doc2);
```
=> ✨ Introduce PdfMaker class

.github/workflows/test-build.yml, CHANGELOG.md, package.json, src/api/PdfMaker.ts, src/api/layout.ts, src/base64.test.ts, src/base64.ts, src/data-loader.test.ts, src/data-loader.ts, src/font-store.ts, src/fs.ts, src/image-store.test.ts, src/image-store.ts, src/images.test.ts, src/images.ts, tsconfig.json
Images used to be registered in the document definition. In v0.5.4, support for loading images directly from the file system was added. However, this feature gives the library access to all files on the system, which may be a security concern.
This commit adds support for including images by a URL. The `image` property of an image block now supports `data:`, `file:`, and `http(s):` URLs. File names are interpreted as relative to a resource root that must be set by the `setResourceRoot()` method on the `PdfMaker` class. Compatibility with the previous API is maintained, but the `images` property in a document definition is deprecated.
An `fs` module is introduced to read files from the file system. Since this module is not available in browser environments, it is loaded using dynamic …
=> ✨ Support including images by URL

CHANGELOG.md, README.md, src/api/document.ts, src/read-document.ts, src/render/render-document.ts
Embedding files in a PDF document can be useful for archival purposes. This commit adds support for embedded files via the `embeddedFiles` property in the document definition.
=> ✨ Support embedded files
